#!/usr/bin/env bash

#@brief ~/.bash_profile file (called when logged in)
#@author Quentin Comte-Gaz <quentin@comte-gaz.com>
#@date 4 August 2016
#@license MIT License (contact me if too restrictive)
#@copyright Copyright (c) 2016 Quentin Comte-Gaz
#
#@note This .bash_profile assumes functions.sh, aliases.sh and commands.sh are stored in $PATH_SCRIPTS

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Show a joke
if [ -x /usr/games/fortune ]; then
  echo "--------------------------"
  /usr/games/fortune -s
  echo "--------------------------"
fi


if [ -f "$PATH_SCRIPTS"/functions.sh ]; then
  source "$PATH_SCRIPTS"/functions.sh

  # Show weather
  showWeather Grenoble
fi


# Function to run upon exit of shell
function _exit()
{
  echo -e "Don't leave me like that :'("
}
trap _exit EXIT
